trigger:
- main


# strategy:
#   matrix:
#     linux: 
#       OperatingSystem: 'ubuntu-latest'
#     macos:
#       OperatingSystem: 'macos-latest'
#     windows:
#       OperatingSystem: 'windows-latest'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the Build"
- stage: DevDeploy
  jobs:
  # - job: BuildJob
  #   steps:
  #   - bash: echo "Start Dev Deploy"
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev
- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to QA


# steps:
# - script: echo Running on $(OperatingSystem)
#   displayName: 'Run a one-line script'


