trigger:
- main

resources:
- repo: self

variables:
  tag: 27
  # '$(Build.BuildId)'

stages:

# stage 1
# Build Docker image
# Publish the K8s files

- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     containerRegistry: 'sheywayne-docker-hub'
    #     repository: 'sheywayne/currency-exchange-devops'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     tags: '$(tag)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
       buildType: 'current'
       artifactName: 'manifests'
       itemPattern: '**/*.yaml'
       targetPath: '$(System.ArtifactsDirectory)'
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'Azure-kubernetes-connection'
        namespace: 'default'
        manifests: '(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'sheywayne/currency-exchange-devops:$(tag)'
# Stage 2
# Download the K8s Files
# Deploy to K8s clusters with docker image
